### ISSUE TITLE
Ugly Errors when building with v1.0.3 and Android 22

### ISSUE THREAD

**Issue by dwhogg** [mesmotronic/cordova-plugin-fullscreen#14]
## This might be helpful if someone else grabs the latest plugin version and gets the errors below.
Version 1.0.2 works fine with Android, but as documented, 1.0.3 targets Android 23!

Fix is either to specify 1.0.2, or use the correct Android SDK (23)!

### Errors when building with incorrect Android SDK version:

FullScreenPlugin.java:17: error: cannot find symbol
import android.view.SearchEvent;

FullScreenPlugin.java:392: error: cannot find symbol
public boolean onSearchRequested(SearchEvent event)

FullScreenPlugin.java:362: error: method does not override or implement a method from a supertype

FullScreenPlugin.java:365: error: method onWindowStartingActionMode in interface android.view.Window.Callback cannot be applied to given types;

**Comment by MaicolBen** [comment]
I have the same error with the same backtrace (with different line numbers, except the first one). Do I have to downgrade or upgrade cordova-android?

**Comment by neilrackett** [comment]
Upgrade to `android@5.0.0` or use `cordova-plugin-fullscreen@1.0.2`

**Comment by neilrackett** [comment]
We're taking a slightly different approach to maintaining immersive mode in release 1.1.0, so you should no longer see errors using this plugin with API 22.
